// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _UI_COMP_BUTTON_H
#define _UI_COMP_BUTTON_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Button
#define UI_COMP_BUTTON_BUTTON 0
#define UI_COMP_BUTTON_LABEL1 1
#define UI_COMP_BUTTON_CONTAINER1 2
#define UI_COMP_BUTTON_CONTAINER1_IMAGE3 3
#define _UI_COMP_BUTTON_NUM 4
lv_obj_t * ui_Button_create(lv_obj_t * comp_parent);
void ui_event_comp_Button_Button(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
