// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
void ULeaveR_Animation (lv_obj_t *TargetObject,int delay);
void LoadRSU_Animation (lv_obj_t *TargetObject,int delay);
void OleaveR_Animation (lv_obj_t *TargetObject,int delay);
void LoadU_Animation (lv_obj_t *TargetObject,int delay);
void OLeaveU_Animation (lv_obj_t *TargetObject,int delay);
void LoadL_Animation (lv_obj_t *TargetObject,int delay);
void OLeaveD_Animation (lv_obj_t *TargetObject,int delay);
void LoadDS_Animation (lv_obj_t *TargetObject,int delay);
void LoadD_Animation (lv_obj_t *TargetObject,int delay);
void ULeaveL_Animation (lv_obj_t *TargetObject,int delay);
void LoadRS_Animation (lv_obj_t *TargetObject,int delay);
void LoadR_Animation (lv_obj_t *TargetObject,int delay);
void LoadUS_Animation (lv_obj_t *TargetObject,int delay);
void LoadLS_Animation (lv_obj_t *TargetObject,int delay);
// CUSTOM
void ui_where_from (lv_event_t *e);
// SCREEN: ui_QDscreen
void ui_QDscreen_screen_init (void);
lv_obj_t *ui_QDscreen;
void ui_event_QDscreenQDimg (lv_event_t *e);
lv_obj_t *ui_QDscreenQDimg;
// CUSTOM VARIABLES

// SCREEN: ui_APP
void ui_APP_screen_init (void);
void ui_event_APP (lv_event_t *e);
lv_obj_t *ui_APP;
void ui_event_APPseting_Button (lv_event_t *e);
lv_obj_t *ui_APPseting;
lv_obj_t *ui_APPfolder;
void ui_event_APPmap_Button (lv_event_t *e);
lv_obj_t *ui_APPmap;
void ui_event_APPbicycle_Button (lv_event_t *e);
lv_obj_t *ui_APPbicycle;
// CUSTOM VARIABLES

// SCREEN: ui_SETING
void ui_SETING_screen_init (void);
void ui_event_SETING (lv_event_t *e);
lv_obj_t *ui_SETING;
lv_obj_t *ui_SETINGSet;
lv_obj_t *ui_SETINGXTong;
lv_obj_t *ui_SETINGLJie;
lv_obj_t *ui_SETINGWZi;
lv_obj_t *ui_SETINGXSi;
lv_obj_t *ui_SETINGAQuan;
lv_obj_t *ui_SETINGCXu;
lv_obj_t *ui_SETINGDCi;
lv_obj_t *ui_SETINGGYu;
lv_obj_t *ui_SETINGQTa;
lv_obj_t *ui_SETINGdownline;
// CUSTOM VARIABLES

// SCREEN: ui_Bicycle
void ui_Bicycle_screen_init (void);
void ui_event_Bicycle (lv_event_t *e);
lv_obj_t *ui_Bicycle;
lv_obj_t *ui_BicycleBAR;
lv_obj_t *ui_BicycleImage5;
lv_obj_t *ui_BicycleImage4;
lv_obj_t *ui_BicycleImage7;
lv_obj_t *ui_BicycleImage8;
lv_obj_t *ui_BicycleImage9;
lv_obj_t *ui_BicycleImage10;
lv_obj_t *ui_BicycleImage11;
lv_obj_t *ui_BicycleImage12;
lv_obj_t *ui_BicycleContainer4;
lv_obj_t *ui_BicycleContainer5;
lv_obj_t *ui_BicycleContainer6;
void ui_event_BicycleRunU (lv_event_t *e);
lv_obj_t *ui_BicycleRunU;
lv_obj_t *ui_BicycleImage2;
// CUSTOM VARIABLES

// SCREEN: ui_Map
void ui_Map_screen_init (void);
lv_obj_t *ui_Map;
void ui_event_MapRunD (lv_event_t *e);
lv_obj_t *ui_MapRunD;
lv_obj_t *ui_MapImage14;
lv_obj_t *ui_MapPanel2;
lv_obj_t *ui_MapLabel3;
lv_obj_t *ui_MapImage13;
lv_obj_t *ui_MapPanel4;
lv_obj_t *ui_MapImage15;
lv_obj_t *ui_MapImage16;
// CUSTOM VARIABLES
// EVENTS
lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
const lv_img_dsc_t *ui_imgset_image_[1] = {&ui_img_image_2_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
#error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP != 1
#error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void ULeaveR_Animation (lv_obj_t *TargetObject,int delay)
{
    ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_mem_alloc (sizeof (ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init (&PropertyAnimation_0);
    lv_anim_set_time (&PropertyAnimation_0,1000);
    lv_anim_set_user_data (&PropertyAnimation_0,PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb (&PropertyAnimation_0,_ui_anim_callback_set_x);
    lv_anim_set_values (&PropertyAnimation_0,0,-100);
    lv_anim_set_path_cb (&PropertyAnimation_0,lv_anim_path_ease_out);
    lv_anim_set_delay (&PropertyAnimation_0,delay + 0);
    lv_anim_set_deleted_cb (&PropertyAnimation_0,_ui_anim_callback_free_user_data);
    lv_anim_set_playback_time (&PropertyAnimation_0,0);
    lv_anim_set_playback_delay (&PropertyAnimation_0,0);
    lv_anim_set_repeat_count (&PropertyAnimation_0,0);
    lv_anim_set_repeat_delay (&PropertyAnimation_0,0);
    lv_anim_set_early_apply (&PropertyAnimation_0,false);
    lv_anim_set_get_value_cb (&PropertyAnimation_0,&_ui_anim_callback_get_x);
    lv_anim_start (&PropertyAnimation_0);
    ui_anim_user_data_t *PropertyAnimation_1_user_data = lv_mem_alloc (sizeof (ui_anim_user_data_t));
    PropertyAnimation_1_user_data->target = TargetObject;
    PropertyAnimation_1_user_data->val = -1;
    lv_anim_t PropertyAnimation_1;
    lv_anim_init (&PropertyAnimation_1);
    lv_anim_set_time (&PropertyAnimation_1,1000);
    lv_anim_set_user_data (&PropertyAnimation_1,PropertyAnimation_1_user_data);
    lv_anim_set_custom_exec_cb (&PropertyAnimation_1,_ui_anim_callback_set_opacity);
    lv_anim_set_values (&PropertyAnimation_1,255,100);
    lv_anim_set_path_cb (&PropertyAnimation_1,lv_anim_path_linear);
    lv_anim_set_delay (&PropertyAnimation_1,delay + 0);
    lv_anim_set_deleted_cb (&PropertyAnimation_1,_ui_anim_callback_free_user_data);
    lv_anim_set_playback_time (&PropertyAnimation_1,0);
    lv_anim_set_playback_delay (&PropertyAnimation_1,0);
    lv_anim_set_repeat_count (&PropertyAnimation_1,0);
    lv_anim_set_repeat_delay (&PropertyAnimation_1,0);
    lv_anim_set_early_apply (&PropertyAnimation_1,false);
    lv_anim_set_get_value_cb (&PropertyAnimation_1,&_ui_anim_callback_get_opacity);
    lv_anim_start (&PropertyAnimation_1);
}
void LoadRSU_Animation (lv_obj_t *TargetObject,int delay)
{
    ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_mem_alloc (sizeof (ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init (&PropertyAnimation_0);
    lv_anim_set_time (&PropertyAnimation_0,900);
    lv_anim_set_user_data (&PropertyAnimation_0,PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb (&PropertyAnimation_0,_ui_anim_callback_set_x);
    lv_anim_set_values (&PropertyAnimation_0,220,0);
    lv_anim_set_path_cb (&PropertyAnimation_0,lv_anim_path_ease_out);
    lv_anim_set_delay (&PropertyAnimation_0,delay + 0);
    lv_anim_set_deleted_cb (&PropertyAnimation_0,_ui_anim_callback_free_user_data);
    lv_anim_set_playback_time (&PropertyAnimation_0,0);
    lv_anim_set_playback_delay (&PropertyAnimation_0,0);
    lv_anim_set_repeat_count (&PropertyAnimation_0,0);
    lv_anim_set_repeat_delay (&PropertyAnimation_0,0);
    lv_anim_set_early_apply (&PropertyAnimation_0,true);
    lv_anim_set_get_value_cb (&PropertyAnimation_0,&_ui_anim_callback_get_x);
    lv_anim_start (&PropertyAnimation_0);
    ui_anim_user_data_t *PropertyAnimation_1_user_data = lv_mem_alloc (sizeof (ui_anim_user_data_t));
    PropertyAnimation_1_user_data->target = TargetObject;
    PropertyAnimation_1_user_data->val = -1;
    lv_anim_t PropertyAnimation_1;
    lv_anim_init (&PropertyAnimation_1);
    lv_anim_set_time (&PropertyAnimation_1,600);
    lv_anim_set_user_data (&PropertyAnimation_1,PropertyAnimation_1_user_data);
    lv_anim_set_custom_exec_cb (&PropertyAnimation_1,_ui_anim_callback_set_opacity);
    lv_anim_set_values (&PropertyAnimation_1,0,255);
    lv_anim_set_path_cb (&PropertyAnimation_1,lv_anim_path_linear);
    lv_anim_set_delay (&PropertyAnimation_1,delay + 0);
    lv_anim_set_deleted_cb (&PropertyAnimation_1,_ui_anim_callback_free_user_data);
    lv_anim_set_playback_time (&PropertyAnimation_1,0);
    lv_anim_set_playback_delay (&PropertyAnimation_1,0);
    lv_anim_set_repeat_count (&PropertyAnimation_1,0);
    lv_anim_set_repeat_delay (&PropertyAnimation_1,0);
    lv_anim_set_early_apply (&PropertyAnimation_1,true);
    lv_anim_set_get_value_cb (&PropertyAnimation_1,&_ui_anim_callback_get_opacity);
    lv_anim_start (&PropertyAnimation_1);
}
void OleaveR_Animation (lv_obj_t *TargetObject,int delay)
{
    ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_mem_alloc (sizeof (ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init (&PropertyAnimation_0);
    lv_anim_set_time (&PropertyAnimation_0,800);
    lv_anim_set_user_data (&PropertyAnimation_0,PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb (&PropertyAnimation_0,_ui_anim_callback_set_x);
    lv_anim_set_values (&PropertyAnimation_0,0,240);
    lv_anim_set_path_cb (&PropertyAnimation_0,lv_anim_path_ease_out);
    lv_anim_set_delay (&PropertyAnimation_0,delay + 0);
    lv_anim_set_deleted_cb (&PropertyAnimation_0,_ui_anim_callback_free_user_data);
    lv_anim_set_playback_time (&PropertyAnimation_0,0);
    lv_anim_set_playback_delay (&PropertyAnimation_0,0);
    lv_anim_set_repeat_count (&PropertyAnimation_0,0);
    lv_anim_set_repeat_delay (&PropertyAnimation_0,0);
    lv_anim_set_early_apply (&PropertyAnimation_0,true);
    lv_anim_set_get_value_cb (&PropertyAnimation_0,&_ui_anim_callback_get_x);
    lv_anim_start (&PropertyAnimation_0);
}
void LoadU_Animation (lv_obj_t *TargetObject,int delay)
{
    ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_mem_alloc (sizeof (ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init (&PropertyAnimation_0);
    lv_anim_set_time (&PropertyAnimation_0,800);
    lv_anim_set_user_data (&PropertyAnimation_0,PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb (&PropertyAnimation_0,_ui_anim_callback_set_y);
    lv_anim_set_values (&PropertyAnimation_0,-320,0);
    lv_anim_set_path_cb (&PropertyAnimation_0,lv_anim_path_overshoot);
    lv_anim_set_delay (&PropertyAnimation_0,delay + 0);
    lv_anim_set_deleted_cb (&PropertyAnimation_0,_ui_anim_callback_free_user_data);
    lv_anim_set_playback_time (&PropertyAnimation_0,0);
    lv_anim_set_playback_delay (&PropertyAnimation_0,0);
    lv_anim_set_repeat_count (&PropertyAnimation_0,0);
    lv_anim_set_repeat_delay (&PropertyAnimation_0,0);
    lv_anim_set_early_apply (&PropertyAnimation_0,true);
    lv_anim_set_get_value_cb (&PropertyAnimation_0,&_ui_anim_callback_get_y);
    lv_anim_start (&PropertyAnimation_0);
}
void OLeaveU_Animation (lv_obj_t *TargetObject,int delay)
{
    ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_mem_alloc (sizeof (ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init (&PropertyAnimation_0);
    lv_anim_set_time (&PropertyAnimation_0,800);
    lv_anim_set_user_data (&PropertyAnimation_0,PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb (&PropertyAnimation_0,_ui_anim_callback_set_y);
    lv_anim_set_values (&PropertyAnimation_0,0,-330);
    lv_anim_set_path_cb (&PropertyAnimation_0,lv_anim_path_ease_out);
    lv_anim_set_delay (&PropertyAnimation_0,delay + 0);
    lv_anim_set_deleted_cb (&PropertyAnimation_0,_ui_anim_callback_free_user_data);
    lv_anim_set_playback_time (&PropertyAnimation_0,0);
    lv_anim_set_playback_delay (&PropertyAnimation_0,0);
    lv_anim_set_repeat_count (&PropertyAnimation_0,0);
    lv_anim_set_repeat_delay (&PropertyAnimation_0,0);
    lv_anim_set_early_apply (&PropertyAnimation_0,false);
    lv_anim_set_get_value_cb (&PropertyAnimation_0,&_ui_anim_callback_get_y);
    lv_anim_start (&PropertyAnimation_0);
}
void LoadL_Animation (lv_obj_t *TargetObject,int delay)
{
    ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_mem_alloc (sizeof (ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init (&PropertyAnimation_0);
    lv_anim_set_time (&PropertyAnimation_0,800);
    lv_anim_set_user_data (&PropertyAnimation_0,PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb (&PropertyAnimation_0,_ui_anim_callback_set_x);
    lv_anim_set_values (&PropertyAnimation_0,-240,0);
    lv_anim_set_path_cb (&PropertyAnimation_0,lv_anim_path_overshoot);
    lv_anim_set_delay (&PropertyAnimation_0,delay + 0);
    lv_anim_set_deleted_cb (&PropertyAnimation_0,_ui_anim_callback_free_user_data);
    lv_anim_set_playback_time (&PropertyAnimation_0,0);
    lv_anim_set_playback_delay (&PropertyAnimation_0,0);
    lv_anim_set_repeat_count (&PropertyAnimation_0,0);
    lv_anim_set_repeat_delay (&PropertyAnimation_0,0);
    lv_anim_set_early_apply (&PropertyAnimation_0,true);
    lv_anim_set_get_value_cb (&PropertyAnimation_0,&_ui_anim_callback_get_x);
    lv_anim_start (&PropertyAnimation_0);
}
void OLeaveD_Animation (lv_obj_t *TargetObject,int delay)
{
    ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_mem_alloc (sizeof (ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init (&PropertyAnimation_0);
    lv_anim_set_time (&PropertyAnimation_0,800);
    lv_anim_set_user_data (&PropertyAnimation_0,PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb (&PropertyAnimation_0,_ui_anim_callback_set_y);
    lv_anim_set_values (&PropertyAnimation_0,0,330);
    lv_anim_set_path_cb (&PropertyAnimation_0,lv_anim_path_ease_out);
    lv_anim_set_delay (&PropertyAnimation_0,delay + 0);
    lv_anim_set_deleted_cb (&PropertyAnimation_0,_ui_anim_callback_free_user_data);
    lv_anim_set_playback_time (&PropertyAnimation_0,0);
    lv_anim_set_playback_delay (&PropertyAnimation_0,0);
    lv_anim_set_repeat_count (&PropertyAnimation_0,0);
    lv_anim_set_repeat_delay (&PropertyAnimation_0,0);
    lv_anim_set_early_apply (&PropertyAnimation_0,false);
    lv_anim_set_get_value_cb (&PropertyAnimation_0,&_ui_anim_callback_get_y);
    lv_anim_start (&PropertyAnimation_0);
}
void LoadDS_Animation (lv_obj_t *TargetObject,int delay)
{
    ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_mem_alloc (sizeof (ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init (&PropertyAnimation_0);
    lv_anim_set_time (&PropertyAnimation_0,900);
    lv_anim_set_user_data (&PropertyAnimation_0,PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb (&PropertyAnimation_0,_ui_anim_callback_set_y);
    lv_anim_set_values (&PropertyAnimation_0,320,0);
    lv_anim_set_path_cb (&PropertyAnimation_0,lv_anim_path_ease_out);
    lv_anim_set_delay (&PropertyAnimation_0,delay + 0);
    lv_anim_set_deleted_cb (&PropertyAnimation_0,_ui_anim_callback_free_user_data);
    lv_anim_set_playback_time (&PropertyAnimation_0,0);
    lv_anim_set_playback_delay (&PropertyAnimation_0,0);
    lv_anim_set_repeat_count (&PropertyAnimation_0,0);
    lv_anim_set_repeat_delay (&PropertyAnimation_0,0);
    lv_anim_set_early_apply (&PropertyAnimation_0,true);
    lv_anim_set_get_value_cb (&PropertyAnimation_0,&_ui_anim_callback_get_y);
    lv_anim_start (&PropertyAnimation_0);
}
void LoadD_Animation (lv_obj_t *TargetObject,int delay)
{
    ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_mem_alloc (sizeof (ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init (&PropertyAnimation_0);
    lv_anim_set_time (&PropertyAnimation_0,900);
    lv_anim_set_user_data (&PropertyAnimation_0,PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb (&PropertyAnimation_0,_ui_anim_callback_set_x);
    lv_anim_set_values (&PropertyAnimation_0,320,0);
    lv_anim_set_path_cb (&PropertyAnimation_0,lv_anim_path_overshoot);
    lv_anim_set_delay (&PropertyAnimation_0,delay + 0);
    lv_anim_set_deleted_cb (&PropertyAnimation_0,_ui_anim_callback_free_user_data);
    lv_anim_set_playback_time (&PropertyAnimation_0,0);
    lv_anim_set_playback_delay (&PropertyAnimation_0,0);
    lv_anim_set_repeat_count (&PropertyAnimation_0,0);
    lv_anim_set_repeat_delay (&PropertyAnimation_0,0);
    lv_anim_set_early_apply (&PropertyAnimation_0,true);
    lv_anim_set_get_value_cb (&PropertyAnimation_0,&_ui_anim_callback_get_x);
    lv_anim_start (&PropertyAnimation_0);
}
void ULeaveL_Animation (lv_obj_t *TargetObject,int delay)
{
    ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_mem_alloc (sizeof (ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init (&PropertyAnimation_0);
    lv_anim_set_time (&PropertyAnimation_0,1000);
    lv_anim_set_user_data (&PropertyAnimation_0,PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb (&PropertyAnimation_0,_ui_anim_callback_set_x);
    lv_anim_set_values (&PropertyAnimation_0,0,100);
    lv_anim_set_path_cb (&PropertyAnimation_0,lv_anim_path_ease_out);
    lv_anim_set_delay (&PropertyAnimation_0,delay + 0);
    lv_anim_set_deleted_cb (&PropertyAnimation_0,_ui_anim_callback_free_user_data);
    lv_anim_set_playback_time (&PropertyAnimation_0,0);
    lv_anim_set_playback_delay (&PropertyAnimation_0,0);
    lv_anim_set_repeat_count (&PropertyAnimation_0,0);
    lv_anim_set_repeat_delay (&PropertyAnimation_0,0);
    lv_anim_set_early_apply (&PropertyAnimation_0,false);
    lv_anim_set_get_value_cb (&PropertyAnimation_0,&_ui_anim_callback_get_x);
    lv_anim_start (&PropertyAnimation_0);
    ui_anim_user_data_t *PropertyAnimation_1_user_data = lv_mem_alloc (sizeof (ui_anim_user_data_t));
    PropertyAnimation_1_user_data->target = TargetObject;
    PropertyAnimation_1_user_data->val = -1;
    lv_anim_t PropertyAnimation_1;
    lv_anim_init (&PropertyAnimation_1);
    lv_anim_set_time (&PropertyAnimation_1,1000);
    lv_anim_set_user_data (&PropertyAnimation_1,PropertyAnimation_1_user_data);
    lv_anim_set_custom_exec_cb (&PropertyAnimation_1,_ui_anim_callback_set_opacity);
    lv_anim_set_values (&PropertyAnimation_1,255,100);
    lv_anim_set_path_cb (&PropertyAnimation_1,lv_anim_path_linear);
    lv_anim_set_delay (&PropertyAnimation_1,delay + 0);
    lv_anim_set_deleted_cb (&PropertyAnimation_1,_ui_anim_callback_free_user_data);
    lv_anim_set_playback_time (&PropertyAnimation_1,0);
    lv_anim_set_playback_delay (&PropertyAnimation_1,0);
    lv_anim_set_repeat_count (&PropertyAnimation_1,0);
    lv_anim_set_repeat_delay (&PropertyAnimation_1,0);
    lv_anim_set_early_apply (&PropertyAnimation_1,false);
    lv_anim_set_get_value_cb (&PropertyAnimation_1,&_ui_anim_callback_get_opacity);
    lv_anim_start (&PropertyAnimation_1);
}
void LoadRS_Animation (lv_obj_t *TargetObject,int delay)
{
    ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_mem_alloc (sizeof (ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init (&PropertyAnimation_0);
    lv_anim_set_time (&PropertyAnimation_0,900);
    lv_anim_set_user_data (&PropertyAnimation_0,PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb (&PropertyAnimation_0,_ui_anim_callback_set_x);
    lv_anim_set_values (&PropertyAnimation_0,220,0);
    lv_anim_set_path_cb (&PropertyAnimation_0,lv_anim_path_ease_out);
    lv_anim_set_delay (&PropertyAnimation_0,delay + 0);
    lv_anim_set_deleted_cb (&PropertyAnimation_0,_ui_anim_callback_free_user_data);
    lv_anim_set_playback_time (&PropertyAnimation_0,0);
    lv_anim_set_playback_delay (&PropertyAnimation_0,0);
    lv_anim_set_repeat_count (&PropertyAnimation_0,0);
    lv_anim_set_repeat_delay (&PropertyAnimation_0,0);
    lv_anim_set_early_apply (&PropertyAnimation_0,true);
    lv_anim_set_get_value_cb (&PropertyAnimation_0,&_ui_anim_callback_get_x);
    lv_anim_start (&PropertyAnimation_0);
}
void LoadR_Animation (lv_obj_t *TargetObject,int delay)
{
    ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_mem_alloc (sizeof (ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init (&PropertyAnimation_0);
    lv_anim_set_time (&PropertyAnimation_0,900);
    lv_anim_set_user_data (&PropertyAnimation_0,PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb (&PropertyAnimation_0,_ui_anim_callback_set_x);
    lv_anim_set_values (&PropertyAnimation_0,220,0);
    lv_anim_set_path_cb (&PropertyAnimation_0,lv_anim_path_overshoot);
    lv_anim_set_delay (&PropertyAnimation_0,delay + 0);
    lv_anim_set_deleted_cb (&PropertyAnimation_0,_ui_anim_callback_free_user_data);
    lv_anim_set_playback_time (&PropertyAnimation_0,0);
    lv_anim_set_playback_delay (&PropertyAnimation_0,0);
    lv_anim_set_repeat_count (&PropertyAnimation_0,0);
    lv_anim_set_repeat_delay (&PropertyAnimation_0,0);
    lv_anim_set_early_apply (&PropertyAnimation_0,false);
    lv_anim_set_get_value_cb (&PropertyAnimation_0,&_ui_anim_callback_get_x);
    lv_anim_start (&PropertyAnimation_0);
}
void LoadUS_Animation (lv_obj_t *TargetObject,int delay)
{
    ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_mem_alloc (sizeof (ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init (&PropertyAnimation_0);
    lv_anim_set_time (&PropertyAnimation_0,800);
    lv_anim_set_user_data (&PropertyAnimation_0,PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb (&PropertyAnimation_0,_ui_anim_callback_set_y);
    lv_anim_set_values (&PropertyAnimation_0,-320,0);
    lv_anim_set_path_cb (&PropertyAnimation_0,lv_anim_path_ease_out);
    lv_anim_set_delay (&PropertyAnimation_0,delay + 0);
    lv_anim_set_deleted_cb (&PropertyAnimation_0,_ui_anim_callback_free_user_data);
    lv_anim_set_playback_time (&PropertyAnimation_0,0);
    lv_anim_set_playback_delay (&PropertyAnimation_0,0);
    lv_anim_set_repeat_count (&PropertyAnimation_0,0);
    lv_anim_set_repeat_delay (&PropertyAnimation_0,0);
    lv_anim_set_early_apply (&PropertyAnimation_0,true);
    lv_anim_set_get_value_cb (&PropertyAnimation_0,&_ui_anim_callback_get_y);
    lv_anim_start (&PropertyAnimation_0);
}
void LoadLS_Animation (lv_obj_t *TargetObject,int delay)
{
    ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_mem_alloc (sizeof (ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init (&PropertyAnimation_0);
    lv_anim_set_time (&PropertyAnimation_0,800);
    lv_anim_set_user_data (&PropertyAnimation_0,PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb (&PropertyAnimation_0,_ui_anim_callback_set_x);
    lv_anim_set_values (&PropertyAnimation_0,-240,0);
    lv_anim_set_path_cb (&PropertyAnimation_0,lv_anim_path_ease_out);
    lv_anim_set_delay (&PropertyAnimation_0,delay + 0);
    lv_anim_set_deleted_cb (&PropertyAnimation_0,_ui_anim_callback_free_user_data);
    lv_anim_set_playback_time (&PropertyAnimation_0,0);
    lv_anim_set_playback_delay (&PropertyAnimation_0,0);
    lv_anim_set_repeat_count (&PropertyAnimation_0,0);
    lv_anim_set_repeat_delay (&PropertyAnimation_0,0);
    lv_anim_set_early_apply (&PropertyAnimation_0,true);
    lv_anim_set_get_value_cb (&PropertyAnimation_0,&_ui_anim_callback_get_x);
    lv_anim_start (&PropertyAnimation_0);
}

///////////////////// FUNCTIONS ////////////////////
void ui_event_QDscreenQDimg (lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code (e);

    if (event_code == LV_EVENT_GESTURE)
    {
        if ((lv_indev_get_gesture_dir (lv_indev_get_act ()) == LV_DIR_LEFT))
        {
            _ui_screen_change (&ui_APP,LV_SCR_LOAD_ANIM_NONE,1000,0,&ui_APP_screen_init);
            LoadRSU_Animation (ui_APP,0);
        } else if ((lv_indev_get_gesture_dir (lv_indev_get_act ()) == LV_DIR_BOTTOM))
        {
            _ui_screen_change (&ui_SETING,LV_SCR_LOAD_ANIM_NONE,1000,0,&ui_SETING_screen_init);
            LoadU_Animation (ui_SETING,0);
            int num = 1;
            lv_msg_send (2,&num);
        } else if ((lv_indev_get_gesture_dir (lv_indev_get_act ()) == LV_DIR_TOP))
        {
            _ui_screen_change (&ui_Bicycle,LV_SCR_LOAD_ANIM_NONE,1000,0,&ui_Bicycle_screen_init);
            LoadDS_Animation (ui_Bicycle,0);
        }
    }
}
void ui_event_APP (lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code (e);

    if (event_code == LV_EVENT_GESTURE)
    {
        if ((lv_indev_get_gesture_dir (lv_indev_get_act ()) == LV_DIR_RIGHT))
        {
            _ui_screen_change (&ui_QDscreen,LV_SCR_LOAD_ANIM_FADE_ON,800,0,&ui_QDscreen_screen_init);
            OleaveR_Animation (ui_APP,0);
        }
    }
}

void ui_event_APPseting_Button (lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code (e);

    if (event_code == LV_EVENT_CLICKED)
    {
        _ui_screen_change (&ui_SETING,LV_SCR_LOAD_ANIM_NONE,300,0,&ui_SETING_screen_init);
        LoadU_Animation (ui_SETING,0);
        int num = 2;
        lv_msg_send (2,&num);
    }
}

void ui_event_APPmap_Button (lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code (e);

    if (event_code == LV_EVENT_CLICKED)
    {
        _ui_screen_change (&ui_Map,LV_SCR_LOAD_ANIM_NONE,500,0,&ui_Map_screen_init);
        LoadL_Animation (ui_Map,0);
        ULeaveL_Animation (ui_APP,0);
    }
}

void ui_event_APPbicycle_Button (lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code (e);

    if (event_code == LV_EVENT_CLICKED)
    {
        _ui_screen_change (&ui_Bicycle,LV_SCR_LOAD_ANIM_NONE,500,0,&ui_Bicycle_screen_init);
        LoadL_Animation (ui_Bicycle,0);
        ULeaveL_Animation (ui_APP,0);
    }
}

void ui_event_SETING (lv_event_t *e)
{
    static  int num = 1;
    lv_event_code_t event_code = lv_event_get_code (e);
    if (event_code == LV_EVENT_MSG_RECEIVED)
    {
        lv_msg_t *m = lv_event_get_msg (e);
        num = *(int *)lv_msg_get_payload (m);
    }
    if (event_code == LV_EVENT_SCROLL_END)
    {
        OLeaveU_Animation (ui_SETING,0);
        if(num == 1)
            _ui_screen_change (&ui_QDscreen,LV_SCR_LOAD_ANIM_FADE_OUT,800,0,&ui_QDscreen_screen_init);
        if(num == 2)
            _ui_screen_change (&ui_APP,LV_SCR_LOAD_ANIM_FADE_ON,800,0,&ui_APP_screen_init);
    }
}

void ui_event_Bicycle (lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code (e);

    if (event_code == LV_EVENT_GESTURE)
    {
        if ((lv_indev_get_gesture_dir (lv_indev_get_act ()) == LV_DIR_BOTTOM))
        {
            _ui_screen_change (&ui_QDscreen,LV_SCR_LOAD_ANIM_FADE_OUT,500,0,&ui_QDscreen_screen_init);
            OLeaveD_Animation (ui_Bicycle,0);
        }
        if ((lv_indev_get_gesture_dir (lv_indev_get_act ()) == LV_DIR_LEFT))
        {
            _ui_screen_change (&ui_APP,LV_SCR_LOAD_ANIM_FADE_ON,500,0,&ui_APP_screen_init);
            ULeaveR_Animation (ui_Bicycle,0);
        }
        if ((lv_indev_get_gesture_dir (lv_indev_get_act ()) == LV_DIR_TOP))
        {
            _ui_screen_change (&ui_Map,LV_SCR_LOAD_ANIM_NONE,500,0,&ui_Map_screen_init);
            LoadDS_Animation (ui_Map,0);
        }
    }
}

void ui_event_BicycleRunU (lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code (e);

    if (event_code == LV_EVENT_CLICKED)
    {
        _ui_screen_change (&ui_Map,LV_SCR_LOAD_ANIM_NONE,500,0,&ui_Map_screen_init);
        LoadDS_Animation (ui_Map,0);
    }
}

void ui_event_Map (lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code (e);

    if (event_code == LV_EVENT_GESTURE)
    {
        if ((lv_indev_get_gesture_dir (lv_indev_get_act ()) == LV_DIR_BOTTOM))
        {
            _ui_screen_change (&ui_Bicycle,LV_SCR_LOAD_ANIM_FADE_OUT,500,0,&ui_Bicycle_screen_init);
            OLeaveD_Animation (ui_Map,0);
        }

        if ((lv_indev_get_gesture_dir (lv_indev_get_act ()) == LV_DIR_LEFT))
        {
            _ui_screen_change (&ui_APP,LV_SCR_LOAD_ANIM_FADE_ON,500,0,&ui_APP_screen_init);
            ULeaveR_Animation (ui_Map,0);
        }
    }
}
void ui_event_MapRunD (lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code (e);

    if (event_code == LV_EVENT_CLICKED)
    {
        _ui_screen_change (&ui_Bicycle,LV_SCR_LOAD_ANIM_FADE_OUT,500,0,&ui_Bicycle_screen_init);
        OLeaveD_Animation (ui_Map,0);
    }

}
//CUSTOM

///////////////////// SCREENS ////////////////////

void ui_init (void)
{
    LV_EVENT_GET_COMP_CHILD = lv_event_register_id ();
    lv_msg_init ();
    lv_disp_t *dispp = lv_disp_get_default ();
    lv_theme_t *theme = lv_theme_default_init (dispp,lv_palette_main (LV_PALETTE_BLUE),lv_palette_main (LV_PALETTE_RED),
                                               false,LV_FONT_DEFAULT);
    lv_disp_set_theme (dispp,theme);
    ui_QDscreen_screen_init ();
    ui_APP_screen_init ();
    ui_SETING_screen_init ();
    ui_Bicycle_screen_init ();
    ui_Map_screen_init ();
    ui____initial_actions0 = lv_obj_create (NULL);
    lv_disp_load_scr (ui_QDscreen);
}
