// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"


const ui_theme_variable_t _ui_theme_color_RED[2] = {0xF64031, 0xF64031};
const ui_theme_variable_t _ui_theme_alpha_RED[2] = {255, 255};

const ui_theme_variable_t _ui_theme_color_BLUE[2] = {0x2095F6, 0x2095F6};
const ui_theme_variable_t _ui_theme_alpha_BLUE[2] = {255, 255};

const ui_theme_variable_t _ui_theme_color_CHROME_YELLOW[2] = {0xFF9933, 0xFF9933};
const ui_theme_variable_t _ui_theme_alpha_CHROME_YELLOW[2] = {255, 255};
uint8_t ui_theme_idx = UI_THEME_YEE;


void ui_theme_set(uint8_t theme_idx)
{
    ui_theme_idx = theme_idx;
    _ui_theme_set_variable_styles(UI_VARIABLE_STYLES_MODE_FOLLOW);
}

