// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"

void ULeaveR_Animation(lv_obj_t * TargetObject, int delay);
void LoadRSU_Animation(lv_obj_t * TargetObject, int delay);
void OleaveR_Animation(lv_obj_t * TargetObject, int delay);
void LoadU_Animation(lv_obj_t * TargetObject, int delay);
void OLeaveU_Animation(lv_obj_t * TargetObject, int delay);
void LoadL_Animation(lv_obj_t * TargetObject, int delay);
void OLeaveD_Animation(lv_obj_t * TargetObject, int delay);
void LoadDS_Animation(lv_obj_t * TargetObject, int delay);
void LoadD_Animation(lv_obj_t * TargetObject, int delay);
void ULeaveL_Animation(lv_obj_t * TargetObject, int delay);
void LoadRS_Animation(lv_obj_t * TargetObject, int delay);
void LoadR_Animation(lv_obj_t * TargetObject, int delay);
void LoadUS_Animation(lv_obj_t * TargetObject, int delay);
void LoadLS_Animation(lv_obj_t * TargetObject, int delay);

// CUSTOM
void ui_where_from (lv_event_t *e);
// SCREEN: ui_QDscreen
void ui_QDscreen_screen_init(void);
extern lv_obj_t * ui_QDscreen;
void ui_event_QDscreenQDimg(lv_event_t * e);
extern lv_obj_t * ui_QDscreenQDimg;
// CUSTOM VARIABLES

// SCREEN: ui_APP
void ui_APP_screen_init(void);
void ui_event_APP(lv_event_t * e);
extern lv_obj_t * ui_APP;
void ui_event_APPseting_Button(lv_event_t * e);
extern lv_obj_t * ui_APPseting;
extern lv_obj_t * ui_APPfolder;
void ui_event_APPmap_Button(lv_event_t * e);
extern lv_obj_t * ui_APPmap;
void ui_event_APPbicycle_Button(lv_event_t * e);
extern lv_obj_t * ui_APPbicycle;
// CUSTOM VARIABLES

// SCREEN: ui_SETING
void ui_SETING_screen_init(void);
void ui_event_SETING(lv_event_t * e);
extern lv_obj_t * ui_SETING;
extern lv_obj_t * ui_SETINGSet;
extern lv_obj_t * ui_SETINGXTong;
extern lv_obj_t * ui_SETINGLJie;
extern lv_obj_t * ui_SETINGWZi;
extern lv_obj_t * ui_SETINGXSi;
extern lv_obj_t * ui_SETINGAQuan;
extern lv_obj_t * ui_SETINGCXu;
extern lv_obj_t * ui_SETINGDCi;
extern lv_obj_t * ui_SETINGGYu;
extern lv_obj_t * ui_SETINGQTa;
extern lv_obj_t * ui_SETINGdownline;
// CUSTOM VARIABLES

// SCREEN: ui_Bicycle
void ui_Bicycle_screen_init(void);
void ui_event_Bicycle(lv_event_t * e);
extern lv_obj_t * ui_Bicycle;
extern lv_obj_t * ui_BicycleBAR;
extern lv_obj_t * ui_BicycleImage5;
extern lv_obj_t * ui_BicycleImage4;
extern lv_obj_t * ui_BicycleImage7;
extern lv_obj_t * ui_BicycleImage8;
extern lv_obj_t * ui_BicycleImage9;
extern lv_obj_t * ui_BicycleImage10;
extern lv_obj_t * ui_BicycleImage11;
extern lv_obj_t * ui_BicycleImage12;
extern lv_obj_t * ui_BicycleContainer4;
extern lv_obj_t * ui_BicycleContainer5;
extern lv_obj_t * ui_BicycleContainer6;
void ui_event_BicycleRunU(lv_event_t * e);
extern lv_obj_t * ui_BicycleRunU;
extern lv_obj_t * ui_BicycleImage2;
// CUSTOM VARIABLES

// SCREEN: ui_Map
void ui_Map_screen_init(void);
extern lv_obj_t * ui_Map;
void ui_event_MapRunD(lv_event_t * e);
void ui_event_Map(lv_event_t * e);
extern lv_obj_t * ui_MapRunD;
extern lv_obj_t * ui_MapImage14;
extern lv_obj_t * ui_MapPanel2;
extern lv_obj_t * ui_MapLabel3;
extern lv_obj_t * ui_MapImage13;
extern lv_obj_t * ui_MapPanel4;
extern lv_obj_t * ui_MapImage15;
extern lv_obj_t * ui_MapImage16;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_image_2_png);    // assets/image 2.png
LV_IMG_DECLARE(ui_img_png_png);    // assets/PNG.png
LV_IMG_DECLARE(ui_img_settings_png);    // assets/Settings.png
LV_IMG_DECLARE(ui_img_folders_png);    // assets/Folders.png
LV_IMG_DECLARE(ui_img_navigation_png);    // assets/Navigation.png
LV_IMG_DECLARE(ui_img_bicycle_png);    // assets/Bicycle.png
LV_IMG_DECLARE(ui_img_electronics_png);    // assets/Electronics.png
LV_IMG_DECLARE(ui_img_1837598647);    // assets/Wi-Fi.png
LV_IMG_DECLARE(ui_img_gps_signal_png);    // assets/GPS Signal.png
LV_IMG_DECLARE(ui_img_lcd_png);    // assets/LCD.png
LV_IMG_DECLARE(ui_img_contact_png);    // assets/Contact.png
LV_IMG_DECLARE(ui_img_folder_tree_png);    // assets/Folder Tree.png
LV_IMG_DECLARE(ui_img_battery_png);    // assets/Battery.png
LV_IMG_DECLARE(ui_img_info_png);    // assets/Info.png
LV_IMG_DECLARE(ui_img_view_more_png);    // assets/View More.png
LV_IMG_DECLARE(ui_img_map_marker_png);    // assets/Map Marker.png
LV_IMG_DECLARE(ui_img_bluetooth_png);    // assets/Bluetooth.png
LV_IMG_DECLARE(ui_img_thermometer_png);    // assets/Thermometer.png
LV_IMG_DECLARE(ui_img_schedule_png);    // assets/Schedule.png
LV_IMG_DECLARE(ui_img_data_transfer_png);    // assets/Data Transfer.png
LV_IMG_DECLARE(ui_img_internet_of_things_png);    // assets/Internet of Things.png
LV_IMG_DECLARE(ui_img_recharge_battery_png);    // assets/Recharge Battery.png
LV_IMG_DECLARE(ui_img_double_up_png);    // assets/Double Up.png
LV_IMG_DECLARE(ui_img_plus_png);    // assets/Plus.png
LV_IMG_DECLARE(ui_img_minus_png);    // assets/Minus.png
LV_IMG_DECLARE(ui_img_capacitor_png);    // assets/Capacitor.png
LV_IMG_DECLARE(ui_img_circled_play_png);    // assets/Circled Play.png
LV_IMG_DECLARE(ui_img_circuit_png);    // assets/Circuit.png
LV_IMG_DECLARE(ui_img_copy_png);    // assets/Copy.png
LV_IMG_DECLARE(ui_img_downloads_folder_png);    // assets/Downloads Folder.png
LV_IMG_DECLARE(ui_img_favorite_folder_png);    // assets/Favorite Folder.png
LV_IMG_DECLARE(ui_img_folder_png);    // assets/Folder.png
LV_IMG_DECLARE(ui_img_games_folder_png);    // assets/Games Folder.png
LV_IMG_DECLARE(ui_img_general_warning_sign_png);    // assets/General Warning Sign.png
LV_IMG_DECLARE(ui_img_heater_resistor_png);    // assets/Heater Resistor.png
LV_IMG_DECLARE(ui_img_insert_button_png);    // assets/Insert Button.png
LV_IMG_DECLARE(ui_img_integrated_circuit_png);    // assets/Integrated Circuit.png
LV_IMG_DECLARE(ui_img_led_diode_png);    // assets/LED Diode.png
LV_IMG_DECLARE(ui_img_micro_sd_png);    // assets/Micro SD.png
LV_IMG_DECLARE(ui_img_move_node_down_png);    // assets/Move Node Down.png
LV_IMG_DECLARE(ui_img_movies_folder_png);    // assets/Movies Folder.png
LV_IMG_DECLARE(ui_img_music_folder_png);    // assets/Music Folder.png
LV_IMG_DECLARE(ui_img_my_location_png);    // assets/My Location.png
LV_IMG_DECLARE(ui_img_nintendo_switch_handheld_png);    // assets/Nintendo Switch Handheld.png
LV_IMG_DECLARE(ui_img_opened_folder_png);    // assets/Opened Folder.png
LV_IMG_DECLARE(ui_img_pause_button_png);    // assets/Pause Button.png
LV_IMG_DECLARE(ui_img_processor_png);    // assets/Processor.png
LV_IMG_DECLARE(ui_img_resistor_png);    // assets/Resistor.png
LV_IMG_DECLARE(ui_img_signpost_png);    // assets/Signpost.png
LV_IMG_DECLARE(ui_img_stop_circled_png);    // assets/Stop Circled.png
LV_IMG_DECLARE(ui_img_toggle_off_png);    // assets/Toggle Off.png
LV_IMG_DECLARE(ui_img_toggle_on_png);    // assets/Toggle On.png
LV_IMG_DECLARE(ui_img_transistor_png);    // assets/Transistor.png
LV_IMG_DECLARE(ui_img_zip_png);    // assets/ZIP.png

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
