// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"


void ui_event_comp_Button_Button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t ** comp_Button = lv_event_get_user_data(e);

    if(event_code == LV_EVENT_CLICKED) {
       
    }
}

// COMPONENT Button

lv_obj_t * ui_Button_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_Button;
    cui_Button = lv_btn_create(comp_parent);
    lv_obj_set_width(cui_Button, 200);
    lv_obj_set_height(cui_Button, 30);
    lv_obj_set_y(cui_Button, 12);
    lv_obj_set_x(cui_Button, lv_pct(0));
    lv_obj_set_align(cui_Button, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(cui_Button, LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_clear_flag(cui_Button, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(cui_Button, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(cui_Button, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_CHROME_YELLOW);
    ui_object_set_themeable_style_property(cui_Button, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_CHROME_YELLOW);
    lv_obj_set_style_shadow_color(cui_Button, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(cui_Button, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(cui_Button, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_Button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(cui_Button, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_Button, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(cui_Button, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(cui_Button, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    lv_obj_t * cui_Label1;
    cui_Label1 = lv_label_create(cui_Button);
    lv_obj_set_width(cui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_Label1, LV_ALIGN_CENTER);

    lv_obj_t * cui_Container1;
    cui_Container1 = lv_obj_create(cui_Button);
    lv_obj_remove_style_all(cui_Container1);
    lv_obj_set_width(cui_Container1, 26);
    lv_obj_set_height(cui_Container1, 26);
    lv_obj_set_align(cui_Container1, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(cui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(cui_Container1, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_Container1, lv_color_hex(0xFFFFCC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Container1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_tiled(cui_Container1, false, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_Container1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_Container1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_Container1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_Container1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(cui_Container1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(cui_Container1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Image3;
    cui_Image3 = lv_img_create(cui_Container1);
    lv_img_set_src(cui_Image3, &ui_img_png_png);
    lv_obj_set_width(cui_Image3, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_height(cui_Image3, LV_SIZE_CONTENT);    /// 64
    lv_obj_set_align(cui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_Image3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(cui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(cui_Image3, 100);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_BUTTON_NUM);
    children[UI_COMP_BUTTON_BUTTON] = cui_Button;
    children[UI_COMP_BUTTON_LABEL1] = cui_Label1;
    children[UI_COMP_BUTTON_CONTAINER1] = cui_Container1;
    children[UI_COMP_BUTTON_CONTAINER1_IMAGE3] = cui_Image3;
    lv_obj_add_event_cb(cui_Button, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_Button, del_component_child_event_cb, LV_EVENT_DELETE, children);
    lv_obj_add_event_cb(cui_Button, ui_event_comp_Button_Button, LV_EVENT_ALL, children);
    ui_comp_Button_create_hook(cui_Button);
    return cui_Button;
}

