// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_APP_screen_init(void)
{
    ui_APP = lv_obj_create(NULL);
    lv_obj_add_flag(ui_APP, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_APP, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_APP, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_APP, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_APPseting = ui_Button_create(ui_APP);
    lv_obj_set_x(ui_APPseting, 0);
    lv_obj_set_y(ui_APPseting, 22);
    lv_obj_set_align(ui_APPseting, LV_ALIGN_TOP_MID);

    lv_label_set_text(ui_comp_get_child(ui_APPseting, UI_COMP_BUTTON_LABEL1), "Text1");


    lv_img_set_src(ui_comp_get_child(ui_APPseting, UI_COMP_BUTTON_CONTAINER1_IMAGE3), &ui_img_settings_png);

    ui_APPfolder = ui_Button_create(ui_APP);
    lv_obj_set_y(ui_APPfolder, 64);
    lv_obj_set_x(ui_APPfolder, lv_pct(0));
    lv_obj_set_align(ui_APPfolder, LV_ALIGN_TOP_MID);

    lv_label_set_text(ui_comp_get_child(ui_APPfolder, UI_COMP_BUTTON_LABEL1), "Text2");


    lv_img_set_src(ui_comp_get_child(ui_APPfolder, UI_COMP_BUTTON_CONTAINER1_IMAGE3), &ui_img_folders_png);

    ui_APPmap = ui_Button_create(ui_APP);
    lv_obj_set_y(ui_APPmap, 106);
    lv_obj_set_x(ui_APPmap, lv_pct(0));

    lv_label_set_text(ui_comp_get_child(ui_APPmap, UI_COMP_BUTTON_LABEL1), "Text3");


    lv_img_set_src(ui_comp_get_child(ui_APPmap, UI_COMP_BUTTON_CONTAINER1_IMAGE3), &ui_img_navigation_png);

    ui_APPbicycle = ui_Button_create(ui_APP);
    lv_obj_set_y(ui_APPbicycle, 148);
    lv_obj_set_x(ui_APPbicycle, lv_pct(0));

    lv_label_set_text(ui_comp_get_child(ui_APPbicycle, UI_COMP_BUTTON_LABEL1), "Text4");


    lv_img_set_src(ui_comp_get_child(ui_APPbicycle, UI_COMP_BUTTON_CONTAINER1_IMAGE3), &ui_img_bicycle_png);

    lv_obj_add_event_cb(ui_APPseting, ui_event_APPseting_Button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_APPmap, ui_event_APPmap_Button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_APPbicycle, ui_event_APPbicycle_Button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_APP, ui_event_APP, LV_EVENT_ALL, NULL);
}
