// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Bicycle_screen_init(void)
{
    ui_Bicycle = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Bicycle, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Bicycle, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bicycle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BicycleBAR = lv_obj_create(ui_Bicycle);
    lv_obj_remove_style_all(ui_BicycleBAR);
    lv_obj_set_height(ui_BicycleBAR, 20);
    lv_obj_set_width(ui_BicycleBAR, lv_pct(100));
    lv_obj_set_align(ui_BicycleBAR, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_BicycleBAR, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_BicycleBAR, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_EVENLY);
    lv_obj_clear_flag(ui_BicycleBAR, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE |
                      LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_BicycleBAR, lv_color_hex(0x333333), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BicycleBAR, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BicycleBAR, lv_color_hex(0xD9D9D9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BicycleBAR, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BicycleBAR, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_BicycleBAR, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BicycleImage5 = lv_img_create(ui_BicycleBAR);
    lv_img_set_src(ui_BicycleImage5, &ui_img_map_marker_png);
    lv_obj_set_width(ui_BicycleImage5, LV_SIZE_CONTENT);   /// 19
    lv_obj_set_height(ui_BicycleImage5, LV_SIZE_CONTENT);    /// 19
    lv_obj_set_x(ui_BicycleImage5, -110);
    lv_obj_set_y(ui_BicycleImage5, -1);
    lv_obj_set_align(ui_BicycleImage5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BicycleImage5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BicycleImage5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_BicycleImage5, 168);

    ui_BicycleImage4 = lv_img_create(ui_BicycleBAR);
    lv_img_set_src(ui_BicycleImage4, &ui_img_bluetooth_png);
    lv_obj_set_width(ui_BicycleImage4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BicycleImage4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BicycleImage4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BicycleImage4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BicycleImage4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_BicycleImage4, 130);

    ui_BicycleImage7 = lv_img_create(ui_BicycleBAR);
    lv_img_set_src(ui_BicycleImage7, &ui_img_thermometer_png);
    lv_obj_set_width(ui_BicycleImage7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BicycleImage7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BicycleImage7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BicycleImage7, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BicycleImage7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_BicycleImage7, 145);

    ui_BicycleImage8 = lv_img_create(ui_BicycleBAR);
    lv_img_set_src(ui_BicycleImage8, &ui_img_schedule_png);
    lv_obj_set_width(ui_BicycleImage8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BicycleImage8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BicycleImage8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BicycleImage8, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BicycleImage8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_BicycleImage8, 169);

    ui_BicycleImage9 = lv_img_create(ui_BicycleBAR);
    lv_img_set_src(ui_BicycleImage9, &ui_img_gps_signal_png);
    lv_obj_set_width(ui_BicycleImage9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BicycleImage9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BicycleImage9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BicycleImage9, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BicycleImage9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_BicycleImage9, 130);

    ui_BicycleImage10 = lv_img_create(ui_BicycleBAR);
    lv_img_set_src(ui_BicycleImage10, &ui_img_data_transfer_png);
    lv_obj_set_width(ui_BicycleImage10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BicycleImage10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BicycleImage10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BicycleImage10, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BicycleImage10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_angle(ui_BicycleImage10, 900);
    lv_img_set_zoom(ui_BicycleImage10, 161);

    ui_BicycleImage11 = lv_img_create(ui_BicycleBAR);
    lv_img_set_src(ui_BicycleImage11, &ui_img_internet_of_things_png);
    lv_obj_set_width(ui_BicycleImage11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BicycleImage11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BicycleImage11, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BicycleImage11, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BicycleImage11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_BicycleImage11, 169);

    ui_BicycleImage12 = lv_img_create(ui_BicycleBAR);
    lv_img_set_src(ui_BicycleImage12, &ui_img_recharge_battery_png);
    lv_obj_set_width(ui_BicycleImage12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BicycleImage12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BicycleImage12, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BicycleImage12, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BicycleImage12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_BicycleImage12, 190);

    ui_BicycleContainer4 = lv_obj_create(ui_Bicycle);
    lv_obj_remove_style_all(ui_BicycleContainer4);
    lv_obj_set_width(ui_BicycleContainer4, 200);
    lv_obj_set_height(ui_BicycleContainer4, 70);
    lv_obj_set_x(ui_BicycleContainer4, 0);
    lv_obj_set_y(ui_BicycleContainer4, 20);
    lv_obj_set_align(ui_BicycleContainer4, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_BicycleContainer4,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_radius(ui_BicycleContainer4, 7, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BicycleContainer4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BicycleContainer4, 64, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BicycleContainer4, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BicycleContainer5 = lv_obj_create(ui_Bicycle);
    lv_obj_remove_style_all(ui_BicycleContainer5);
    lv_obj_set_width(ui_BicycleContainer5, 96);
    lv_obj_set_height(ui_BicycleContainer5, 150);
    lv_obj_set_x(ui_BicycleContainer5, 20);
    lv_obj_set_y(ui_BicycleContainer5, 99);
    lv_obj_clear_flag(ui_BicycleContainer5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BicycleContainer5, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BicycleContainer5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BicycleContainer5, 64, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BicycleContainer5, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BicycleContainer6 = lv_obj_create(ui_Bicycle);
    lv_obj_remove_style_all(ui_BicycleContainer6);
    lv_obj_set_width(ui_BicycleContainer6, 96);
    lv_obj_set_height(ui_BicycleContainer6, 150);
    lv_obj_set_x(ui_BicycleContainer6, 124);
    lv_obj_set_y(ui_BicycleContainer6, 99);
    lv_obj_clear_flag(ui_BicycleContainer6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BicycleContainer6, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BicycleContainer6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BicycleContainer6, 64, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BicycleContainer6, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BicycleRunU = lv_obj_create(ui_Bicycle);
    lv_obj_set_width(ui_BicycleRunU, 240);
    lv_obj_set_height(ui_BicycleRunU, 45);
    lv_obj_set_x(ui_BicycleRunU, 0);
    lv_obj_set_y(ui_BicycleRunU, 15);
    lv_obj_set_align(ui_BicycleRunU, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_BicycleRunU, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BicycleRunU, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BicycleRunU, lv_color_hex(0xECECDA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BicycleRunU, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BicycleImage2 = lv_img_create(ui_BicycleRunU);
    lv_img_set_src(ui_BicycleImage2, &ui_img_double_up_png);
    lv_obj_set_width(ui_BicycleImage2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BicycleImage2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BicycleImage2, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_BicycleImage2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BicycleImage2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_BicycleRunU, ui_event_BicycleRunU, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Bicycle, ui_event_Bicycle, LV_EVENT_ALL, NULL);

}
