// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Map_screen_init(void)
{
    ui_Map = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Map, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Map, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Map, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MapRunD = lv_obj_create(ui_Map);
    lv_obj_set_width(ui_MapRunD, 240);
    lv_obj_set_height(ui_MapRunD, 45);
    lv_obj_set_x(ui_MapRunD, 0);
    lv_obj_set_y(ui_MapRunD, -15);
    lv_obj_set_align(ui_MapRunD, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_MapRunD, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_MapRunD, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MapRunD, lv_color_hex(0xECECDA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MapRunD, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MapImage14 = lv_img_create(ui_MapRunD);
    lv_img_set_src(ui_MapImage14, &ui_img_double_up_png);
    lv_obj_set_width(ui_MapImage14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MapImage14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MapImage14, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_MapImage14, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_MapImage14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_angle(ui_MapImage14, 1800);

    ui_MapPanel2 = lv_obj_create(ui_Map);
    lv_obj_set_width(ui_MapPanel2, 220);
    lv_obj_set_height(ui_MapPanel2, 60);
    lv_obj_set_x(ui_MapPanel2, -20);
    lv_obj_set_y(ui_MapPanel2, 220);
    lv_obj_clear_flag(ui_MapPanel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_MapPanel2, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MapPanel2, lv_color_hex(0xD9D9D9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MapPanel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MapLabel3 = lv_label_create(ui_MapPanel2);
    lv_obj_set_width(ui_MapLabel3, 150);
    lv_obj_set_height(ui_MapLabel3, 40);
    lv_obj_set_x(ui_MapLabel3, 0);
    lv_obj_set_y(ui_MapLabel3, 3);
    lv_obj_set_align(ui_MapLabel3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MapLabel3, "15KM/H");
    lv_obj_set_style_text_align(ui_MapLabel3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MapLabel3, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MapImage13 = lv_img_create(ui_MapPanel2);
    lv_img_set_src(ui_MapImage13, &ui_img_double_up_png);
    lv_obj_set_width(ui_MapImage13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MapImage13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MapImage13, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_MapImage13, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_MapImage13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_angle(ui_MapImage13, -900);

    ui_MapPanel4 = lv_obj_create(ui_Map);
    lv_obj_set_width(ui_MapPanel4, 26);
    lv_obj_set_height(ui_MapPanel4, 80);
    lv_obj_set_x(ui_MapPanel4, 206);
    lv_obj_set_y(ui_MapPanel4, 210);
    lv_obj_clear_flag(ui_MapPanel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MapPanel4, lv_color_hex(0xD9D9D9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MapPanel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_MapPanel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_MapPanel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_MapPanel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_MapPanel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_MapPanel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MapImage15 = lv_img_create(ui_MapPanel4);
    lv_img_set_src(ui_MapImage15, &ui_img_plus_png);
    lv_obj_set_width(ui_MapImage15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MapImage15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MapImage15, 0);
    lv_obj_set_y(ui_MapImage15, 2);
    lv_obj_set_align(ui_MapImage15, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_MapImage15, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_MapImage15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_MapImage15, 219);

    ui_MapImage16 = lv_img_create(ui_MapPanel4);
    lv_img_set_src(ui_MapImage16, &ui_img_minus_png);
    lv_obj_set_width(ui_MapImage16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MapImage16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MapImage16, 0);
    lv_obj_set_y(ui_MapImage16, -2);
    lv_obj_set_align(ui_MapImage16, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_MapImage16, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_MapImage16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_MapImage16, 219);

    lv_obj_add_event_cb(ui_MapRunD, ui_event_MapRunD, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb (ui_Map,ui_event_Map,LV_EVENT_ALL,NULL);
}
