// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_QDscreen_screen_init(void)
{
    ui_QDscreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_QDscreen, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_QDscreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_QDscreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_QDscreenQDimg = lv_img_create(ui_QDscreen);
    lv_img_set_src(ui_QDscreenQDimg, &ui_img_image_2_png);
    lv_obj_set_width(ui_QDscreenQDimg, LV_SIZE_CONTENT);   /// 144
    lv_obj_set_height(ui_QDscreenQDimg, LV_SIZE_CONTENT);    /// 144
    lv_obj_set_align(ui_QDscreenQDimg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_QDscreenQDimg, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CHECKABLE |
                    LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_QDscreenQDimg, LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    lv_obj_add_event_cb(ui_QDscreenQDimg, ui_event_QDscreenQDimg, LV_EVENT_ALL, NULL);
}
