// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_SETING_screen_init(void)
{
    ui_SETING = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SETING, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SETING, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SETING, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SETINGSet = lv_obj_create(ui_SETING);
    lv_obj_remove_style_all(ui_SETINGSet);
    lv_obj_set_width(ui_SETINGSet, lv_pct(100));
    lv_obj_set_height(ui_SETINGSet, lv_pct(100));
    lv_obj_set_align(ui_SETINGSet, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_SETINGSet, LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_clear_flag(ui_SETINGSet, LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE);      /// Flags
    lv_obj_set_scroll_dir(ui_SETINGSet, LV_DIR_VER);

    ui_object_set_themeable_style_property(ui_SETINGSet, LV_PART_SCROLLBAR | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_RED);
    ui_object_set_themeable_style_property(ui_SETINGSet, LV_PART_SCROLLBAR | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_RED);
    ui_object_set_themeable_style_property(ui_SETINGSet, LV_PART_SCROLLBAR | LV_STATE_SCROLLED, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_BLUE);
    ui_object_set_themeable_style_property(ui_SETINGSet, LV_PART_SCROLLBAR | LV_STATE_SCROLLED, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_BLUE);
    ui_object_set_themeable_style_property(ui_SETINGSet, LV_PART_SCROLLBAR | LV_STATE_SCROLLED, LV_STYLE_BG_GRAD_COLOR,
                                           _ui_theme_color_RED);
    lv_obj_set_style_outline_color(ui_SETINGSet, lv_color_hex(0x000000), LV_PART_SCROLLBAR | LV_STATE_SCROLLED);
    lv_obj_set_style_outline_opa(ui_SETINGSet, 255, LV_PART_SCROLLBAR | LV_STATE_SCROLLED);

    ui_SETINGXTong = ui_Button_create(ui_SETINGSet);
    lv_obj_set_y(ui_SETINGXTong, 12);
    lv_obj_set_x(ui_SETINGXTong, lv_pct(0));
    lv_obj_set_align(ui_SETINGXTong, LV_ALIGN_TOP_MID);



    lv_img_set_src(ui_comp_get_child(ui_SETINGXTong, UI_COMP_BUTTON_CONTAINER1_IMAGE3), &ui_img_electronics_png);

    ui_SETINGLJie = ui_Button_create(ui_SETINGSet);
    lv_obj_set_y(ui_SETINGLJie, 50);
    lv_obj_set_x(ui_SETINGLJie, lv_pct(0));



    lv_img_set_src(ui_comp_get_child(ui_SETINGLJie, UI_COMP_BUTTON_CONTAINER1_IMAGE3), &ui_img_1837598647);

    ui_SETINGWZi = ui_Button_create(ui_SETINGSet);
    lv_obj_set_y(ui_SETINGWZi, 88);
    lv_obj_set_x(ui_SETINGWZi, lv_pct(0));



    lv_img_set_src(ui_comp_get_child(ui_SETINGWZi, UI_COMP_BUTTON_CONTAINER1_IMAGE3), &ui_img_gps_signal_png);

    ui_SETINGXSi = ui_Button_create(ui_SETINGSet);
    lv_obj_set_y(ui_SETINGXSi, 126);
    lv_obj_set_x(ui_SETINGXSi, lv_pct(0));



    lv_img_set_src(ui_comp_get_child(ui_SETINGXSi, UI_COMP_BUTTON_CONTAINER1_IMAGE3), &ui_img_lcd_png);

    ui_SETINGAQuan = ui_Button_create(ui_SETINGSet);
    lv_obj_set_y(ui_SETINGAQuan, 164);
    lv_obj_set_x(ui_SETINGAQuan, lv_pct(0));



    lv_img_set_src(ui_comp_get_child(ui_SETINGAQuan, UI_COMP_BUTTON_CONTAINER1_IMAGE3), &ui_img_contact_png);

    ui_SETINGCXu = ui_Button_create(ui_SETINGSet);
    lv_obj_set_y(ui_SETINGCXu, 202);
    lv_obj_set_x(ui_SETINGCXu, lv_pct(0));



    lv_img_set_src(ui_comp_get_child(ui_SETINGCXu, UI_COMP_BUTTON_CONTAINER1_IMAGE3), &ui_img_folder_tree_png);

    ui_SETINGDCi = ui_Button_create(ui_SETINGSet);
    lv_obj_set_y(ui_SETINGDCi, 240);
    lv_obj_set_x(ui_SETINGDCi, lv_pct(0));



    lv_img_set_src(ui_comp_get_child(ui_SETINGDCi, UI_COMP_BUTTON_CONTAINER1_IMAGE3), &ui_img_battery_png);

    ui_SETINGGYu = ui_Button_create(ui_SETINGSet);
    lv_obj_set_y(ui_SETINGGYu, 280);
    lv_obj_set_x(ui_SETINGGYu, lv_pct(0));



    lv_img_set_src(ui_comp_get_child(ui_SETINGGYu, UI_COMP_BUTTON_CONTAINER1_IMAGE3), &ui_img_info_png);

    ui_SETINGQTa = ui_Button_create(ui_SETINGSet);
    lv_obj_set_y(ui_SETINGQTa, 318);
    lv_obj_set_x(ui_SETINGQTa, lv_pct(0));
    lv_obj_add_flag(ui_SETINGQTa, LV_OBJ_FLAG_SNAPPABLE);     /// Flags



    lv_img_set_src(ui_comp_get_child(ui_SETINGQTa, UI_COMP_BUTTON_CONTAINER1_IMAGE3), &ui_img_view_more_png);

    ui_SETINGdownline = lv_label_create(ui_SETINGSet);
    lv_obj_set_width(ui_SETINGdownline, 20);
    lv_obj_set_height(ui_SETINGdownline, 8);
    lv_obj_set_x(ui_SETINGdownline, 0);
    lv_obj_set_y(ui_SETINGdownline, 350);
    lv_obj_set_align(ui_SETINGdownline, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_SETINGdownline, "");
    lv_obj_clear_flag(ui_SETINGdownline,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE |
                      LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_SETINGdownline, LV_SCROLLBAR_MODE_OFF);

    lv_obj_add_event_cb(ui_SETING, ui_event_SETING, LV_EVENT_ALL, NULL);
    lv_msg_subscribe_obj(2, ui_SETING,NULL);
}
